- typeset/math-ext.satyh
I added some math commands. Most of them are the same as the existing commands.
> added some math commands

- graphics.satyh
- path.satyh
- t/test.saty
したこと：
- Pathモジュールを`path.satyh`に分割
- `ellipse`のバグを修正
> separate graphics.satyh and fix `ellipse`

- float.satyg
- int.satyg
- length.satyg
> add equals

- LICENSE
- README.md
- satysfi-lib.opam
I decided to license this project under MIT (mainly because zrbase adopts this license).
I am going to merge this change unless either of you @puripuri2100 and @zeptometer declined.
> Add license

- README.md
- Satyristes
- satysfi-base.opam
Rename the project to satysfi-base.
After this pr is merged I will change the name of repository, too.
> satysfi-lib -> satysfi-base

- Satyristes
- satysfi-base.opam
@na4zagin3 Could you review this change? I wish you to check this patch indeed suffices. It seems like I cannot assign you reviewing when you are not a collaborator of this repository, so I sent you an invitation, check it out please.
> version 1.0.0

- pager.satyh
- t/test.saty
pagerファイルの型が間違っていたので修正しました
@puripuri2100 レビューおねがいしてもいいですか？ 🙏
> fix(pager): fix type signatures

- context.satyh
- font.satyh
> add: Context module

- Satyristes
- satysfi-base.opam
- #27 Fix typo color-ex.satyg in Satyristes by na4zagin3
> version 1.1.1

- .github/workflows/ci.yml
- Satyristes
- satysfi-base.opam
- typeset/code2.satyh
This PR will close #30 by adding satyrographos dependency on https://github.com/zeptometer/SATySFi-fonts-dejavu.
> Add dependency on satysfi-fonts-dejavu

- package.json
- scripts/make-changelog.js
- yarn.lock
Adding a maintenance script to generate changelog since the last release.
> add make-changelog.js

- scripts/release.js
@zeptometer Sorry can you review this again please?
> fix release.js

- Satyristes
- satysfi-base.opam
- #43 fix release.js by nyuichi
- #39 add release.js by nyuichi
- #26 move source files to src by nyuichi
- #24 add make-changelog.js by nyuichi
- #36 Add Option.iter by zeptometer
- #37 Add CrossRef by zeptometer
- #35 Add dependency on satysfi-fonts-dejavu by zeptometer
- #28 Make test cases fail when satysfi does not exist by na4zagin3
> Release 1.2.0

- scripts/make-changelog.js
- scripts/release.js
- scripts/utils.js
Small refactoring of maintenance scripts
@zeptometer 🙏
> retrieve current version from opam file

- __test__/satysrc/generic.saty
- src/base.satyg
- src/typeset/base.satyh
> Fix base.satyg

- __test__/satysrc/generic.saty
- src/__sub__/base-sub.satyg
- src/__sub__/base-sub.satyh
- src/base.satyg
- src/typeset/base.satyh
> もしテキストモードでもfinish的なものが(standaloneを使わずに)実装できるならそれを実装してminor or patch versionだけ上げるのでも良いかなと思いますがテキストモードってそういうことできますかね？ @puripuri2100
https://satysfi.slack.com/archives/CRR5NLJN6/p1584854889016300
I implemented it.
> Fix base's finish function

- __test__/__snapshots__/regression.test.js.snap
- __test__/satysrc/generic.saty
- src/list-ext.satyg
I added `mergesort : ('a Ord.t) implicit -> 'a list -> 'a list`.
reference : https://xaro.hatenablog.jp/entry/2014/02/15/015800
> Add mergesort

- README.md
This pull request adds a build status badge in README.md.
> add status badge

- src/pager.satyh
I added A, B, C Series(ISO 216) and B Series(JIS P 0138).
reference : https://en.wikipedia.org/wiki/ISO_216#Dimensions_of_A,_B_and_C_Series
reference : https://ja.wikipedia.org/wiki/%E7%B4%99%E3%81%AE%E5%AF%B8%E6%B3%95#JIS_(%E6%97%A5%E6%9C%AC)
> Add some page size

- __test__/__snapshots__/regression.test.js.snap
- __test__/satysrc/generic.saty
- src/bool.satyg
- src/float.satyg
- src/int.satyg
I added some safety functions to change string to value.
```
% Int
val to-string : int -> string
val of-string-opt : int ?-> string -> int option
```
```
% Float
val of-string-opt : string -> float option
val to-string : float -> string
```
> Add of-string-opt

- src/base.satyg
- src/list-ext.satyg
- src/option-ext.satyg
- src/result.satyg
- src/stream.satyg
- add many functions
- rename some existing functions (keeping the old names as aliases to them)
- mark some functions as obsoleted
- No actual change involved. I left a mere comment.
> Some expansion to the List, Option, Result, and Stream modules

- satysfi-base.opam
> bump up dependencies

- Satyristes
- satysfi-base.opam
- #125 bump up dependencies by nyuichi
- #124 Make packages persistent as to stage by gfngfn
- #114 Add dependency on satysfi-dist by na4zagin3
- #109 Fix satysfi-it by uemurax
> Release 1.4.0

- src/char.satyg
> Add Char.to-codepoint

- Satyristes
- satysfi-base.opam
- src/float.satyg
> remove zrbase from dependency

- .github/workflows/ci.yml
- satysfi-base.opam
> GH-245: Support satysfi-0.0.7

- Satyristes
- satysfi-base.opam
This release includes the following updates:
- #278 Add some string functions by puripuri2100
- #280 Fix 279 by puripuri2100
- #198 Add big-int by puripuri2100
> GH-281: Release 1.6.0
